### ISSUE TITLE
FileNotFound oval_org.mitre.oval_def_1853.xml

### ISSUE THREAD

**Issue by joshuaperrette** [CISecurity/OVALRepo#1936]
Was following the steps to build a Windows vulnerability xml file and received the following error:

  python3 build_oval_definitions_file.py -o all.windows.vulnerability.xml --family windows --class vulnerability
  INFO: Found 13644 matching OVAL definitions
  INFO: Finding downstream OVAL ids for all definitions
  INFO: Found 67134 downstream OVAL ids
  INFO: Finding paths for 80778 OVAL elements
  INFO: Generating OVAL definition file with 80778 elements
  Traceback (most recent call last):
    File "C:\Users\perrettej\OVALRepo\scripts\build_oval_definitions_file.py", line 186, in <module>
      main()
    File "C:\Users\perrettej\OVALRepo\scripts\build_oval_definitions_file.py", line 140, in main
      OvalGenerator.queue_element_file(element_type, file_path)
    File "C:\Users\perrettej\OVALRepo\scripts\lib_xml.py", line 368, in queue_element_file
      with open(filepath, mode='rt', encoding='utf-8') as xml_file:
  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\perrettej\\OneDrive\\Documents\\OVALRepo\\repository\\definitions\\inventory\\oval_org.mitre.oval_def_1853.xml'

**Comment by joshuaperrette** [comment]
Fixed. Cleared __index__ subdirectories and __pycache__ and rebuilt indexes.
