### ISSUE TITLE
Error building oval definitions

### ISSUE THREAD

**Issue by wmunyan** [CISecurity/OVALRepo#43]
Executed "build_oval_definitions_file.py" first time successfully.  Went through the process of building the indexes, all good... Generated the output file correctly.

Tried to execute the command a second time with a different definition_id, and got this:
```Script
wmunyan\OVALRepo\scripts>python build_oval_definitions_file.py --definition_id oval:org.mitre.oval:def:6716 -o c:\temp\outfile6716.xml
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\git\cmd.py", line 573, in execute
    **subprocess_kwargs
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_oval_definitions_file.py", line 140, in <module>
    main()
  File "build_oval_definitions_file.py", line 68, in main
    query_results = definitions_index.query(query)
  File "C:\Users\bmunyan\Documents\GitHub\Forks\wmunyan\OVALRepo\scripts\lib_search.py", line 74, in query
    self.update()
  File "C:\Users\bmunyan\Documents\GitHub\Forks\wmunyan\OVALRepo\scripts\lib_search.py", line 144, in update
    uncommitted_files = lib_git.get_uncommitted_oval()
  File "C:\Users\bmunyan\Documents\GitHub\Forks\wmunyan\OVALRepo\scripts\lib_git.py", line 39, in get_uncommitted_oval
    for diff in repo.index.diff(repo.head.commit, paths=content_rel_path):
  File "C:\Python34\lib\site-packages\git\index\util.py", line 69, in check_default_index
    return func(self, *args, **kwargs)
  File "C:\Python34\lib\site-packages\git\index\base.py", line 1189, in diff
    return other.diff(self.Index, paths, create_patch, **kwargs)
  File "C:\Python34\lib\site-packages\git\diff.py", line 104, in diff
    proc = self.repo.git.diff(*self._process_diff_args(args), **kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 810, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 576, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: [WinError 2] The system cannot find the file specified
```

**Comment by DavidRies** [comment]
Thanks, bill. I'll fix this.

**Comment by DavidRies** [comment]
Hi Bill, so... this is a bit strange. I can't reproduce it, but I looked into the git-python code raising the exception and it looks like it's failing to run the "git" executable.

Git isn't used when building the index initially, only when updating it. That explains why everything worked the first time (and will work the first time you run this after pulling a new commit).

This might be solved by making sure the Git is in your PATH. Is it? It should probably look something like this: ```c:\Program Files\Git\cmd```

**Comment by wmunyan** [comment]
I did not have Git installed.  Installing, rebooting the vm and re-testing.

**Comment by DavidRies** [comment]
Aha! The scripts require GIT. And, they assume that they are running from within a local working copy (clone). I will add this to the docs.

> On Jul 17, 2015, at 12:46 PM, Bill M <notifications@github.com> wrote:
> 
> I did not have Git installed. Installing, rebooting the vm and re-testing.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CISecurity/OVALRepo/issues/43#issuecomment-122354399>.
> 

-David

--
David E. Ries
Partner
Farnam Hall Ventures 

farnamhallventures.com <http://farnamhallventures.com/>

**Comment by DavidRies** [comment]
Added requirement to docs.
